FROM weaveworksdemos/msd-java:jre-latest

WORKDIR /usr/src/app
COPY target/*.jar ./app.jar
COPY dd-java-agent.jar ./dd-java-agent.jar

RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ./app.jar

RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ./dd-java-agent.jar
 
USER ${SERVICE_USER}

ENTRYPOINT ["/usr/local/bin/java.sh","-javaagent:./dd-java-agent.jar","-jar","./app.jar", "--port=80"]
